group: "laom-labels-default"
seed: 0

lapo:
  num_epochs: 10
  batch_size: 256
  labeled_batch_size: 64
  labeled_loss_coef: 0.001
  cosine_loss: False
  use_aug: True
  future_obs_offset: 10
  learning_rate: 0.0001
  weight_decay: 0.0
  warmup_epochs: 3
  latent_action_dim: 8192
  act_head_dim: 1024
  act_head_dropout: 0.0
  obs_head_dim: 1024
  obs_head_dropout: 0.0
  encoder_scale: 6
  encoder_num_res_blocks: 2
  encoder_dropout: 0.0
  encoder_norm_out: False
  encoder_deep: False
  target_tau: 0.001
  target_update_every: 1
  frame_stack: 3
  # TODO: change to your data and action-labeled data path, eval is optional
  data_path: "data/example-data.hdf5"
  labeled_data_path: "data/example-data.hdf5"
  eval_data_path: "data/example-data.hdf5"

bc:
  num_epochs: 1
  batch_size: 256
  learning_rate: 0.0001
  weight_decay: 0.0 
  warmup_epochs: 0
  encoder_scale: 32
  encoder_num_res_blocks: 2
  encoder_deep: False
  dropout: 0.0
  use_aug: False
  frame_stack: 3
  # TODO: change to your data and DAVIS path
  data_path: "data/example-data.hdf5"
  dcs_backgrounds_path: "DAVIS/JPEGImages/480p"
  dcs_backgrounds_split: "train"
  eval_episodes: 5
  eval_seed: 0

decoder:
  total_updates: 2500
  batch_size: 256
  learning_rate: 0.0003
  weight_decay: 0.0
  warmup_epochs: 0
  hidden_dim: 256
  use_aug: False
  # TODO: change to your DAVIS path
  dcs_backgrounds_path: "DAVIS/JPEGImages/480p"
  dcs_backgrounds_split: "train"
  eval_episodes: 25
  eval_seed: 0