group: "mv-labels-default"
seed: 0
debug_dataloader: true

lapo:
  num_epochs: 400
  batch_size: 32
  labeled_batch_size: 4
  camera_num: 
  view_keys: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  eval_view_keys: [10]
  views_per_instance: 8
  contrastive_loss_coef: 1.0
  triplet_warmup_epochs: 0
  base_margin: 0.2
  labeled_loss_coef: 0.001
  cosine_loss: False
  use_aug: True
  future_obs_offset: 10
  learning_rate: 0.0001
  weight_decay: 0.0
  warmup_epochs: 20
  grad_norm: 1.0
  latent_action_dim: 128
  act_head_dim: 1024
  act_head_dropout: 0.0
  obs_head_dim: 1024
  obs_head_dropout: 0.0
  encoder_scale: 1
  encoder_num_res_blocks: 2
  encoder_dropout: 0.0
  encoder_norm_out: False
  encoder_deep: False
  target_tau: 0.001
  target_update_every: 1
  frame_stack: 1
  seed: 0
  num_workers: 12
  normalize_triplet: False
  loss_type: "infonce"  # "triplet" or "infonce"
  infonce_temperature: 1.0
  # --- False Negative Filtering ---
  filtering_type: "l2" # "none", "l2", "dtw"
  dtw_threshold: 5.0
  l2_threshold: 5.0
  fixed_batch_offset: True
  # TODO: change to your data and action-labeled data path, eval is optional
  data_path: "data/example-data.hdf5"
  labeled_data_path: "data/example-data.hdf5"
  eval_data_path: "data/example-data.hdf5"
  

bc:
  num_epochs: 1
  batch_size: 256
  learning_rate: 0.00001
  weight_decay: 0.0 
  warmup_epochs: 0
  encoder_scale: 32
  encoder_num_res_blocks: 2
  encoder_deep: False
  dropout: 0.0
  use_aug: False
  frame_stack: 3
  # TODO: change to your data and DAVIS path
  data_path: "data/example-data.hdf5"
  dcs_backgrounds_path: "DAVIS/JPEGImages/480p"
  dcs_backgrounds_split: "train"
  eval_episodes: 5
  eval_seed: 0
  # Multi-view related settings
  camera_num: 21
  view_keys: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  views_per_instance: 1
  fixed_offset: 1

decoder:
  total_updates: 2500
  batch_size: 256
  learning_rate: 0.0003
  weight_decay: 0.0
  warmup_epochs: 0
  hidden_dim: 256
  use_aug: False
  # TODO: change to your DAVIS path
  dcs_backgrounds_path: "DAVIS/JPEGImages/480p"
  dcs_backgrounds_split: "train"
  eval_episodes: 25
  eval_seed: 0
  # Multi-view related settings (inherited from BCConfig)
  camera_num: 20
  view_keys: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  views_per_instance: 1
  frame_stack: 3
  fixed_offset: 1